Repository VishnuAmit/VLearnUp-ELearningHub, pull requests merged in 2024-10, with the labels that each got.

#7 Enhancement of Dashboard UI
  src/components/Footer.js
  src/components/FrameComponent.js
  src/components/FrameComponent4.js
  src/components/LatestUpdates.js
  src/components/LearningPaths.js
  src/components/PlatformOverview.js
  src/components/SmartNotesCard.js
  src/components/Testimonials.js
  src/pages/SignUpScreen.js
Labels: bug, good first issue, Hacktoberfest

#18 Navbar update issue #9
  src/components/FrameComponent.js
  src/components/FrameComponent2.js
  src/components/LatestUpdates.js
  src/components/MainHeader.js
  src/components/PlatformOverview.js
  src/pages/ELearning.js
Labels: good first issue, Hacktoberfest

#21 Fixed the aligment and used the old layout added NewsAPI based articles #13
  src/components/LatestUpdates.js
Labels: bug, good first issue, Hacktoberfest

#26 Fix dependency version errors
  backend/package-lock.json
  backend/package.json
Labels: bug, Hacktoberfest

#29 Fixed null property runtime error in development mode
  src/components/LatestUpdates.js
Labels: bug, Hacktoberfest

#24 Implement Form Handling and Dynamic Dashboard Update in streamfinder.js , Dashboard.js & ProfileCard.js
  src/components/ProfileCard.js
  src/pages/CourseInputModal.js
  src/pages/CourseInputModalStyle.css
  src/pages/Dashboard.js
  src/pages/Streamfinder.js
  src/pages/StreamfinderStyle.css
Labels: good first issue, Hacktoberfest, Hacktoberfest-accepted

#31 enhancements
  package-lock.json
  src/components/FrameComponent4.js
  src/components/MainHeader.js
  src/pages/ELearning.js
Labels: enhancement, Hacktoberfest, Hacktoberfest-accepted

#33 Fixed Text Alignment
  package-lock.json
  src/components/CoursesGrid.js
Labels: enhancement, Hacktoberfest

#34 Fixed a few problems on Dashboard
  src/components/FrameComponent3.js
  src/components/FrameComponent4.js
  src/components/LatestUpdates.js
  src/components/MainHeader.js
  src/components/SmartNotesCard.js
  src/components/Testimonials.js
  src/pages/ELearning.js
Labels: enhancement, Hacktoberfest, Hacktoberfest-accepted, level-3

#40 Header made Responsive, Fixed Hero Bg and Fixed Header Position
  public/tilt.svg
  src/components/FrameComponent4.js
  src/components/MainHeader.js
  src/global.css
  src/pages/ELearning.js
Labels: enhancement, Hacktoberfest, Level 2, Hacktoberfest-accepted

#44 Feature#43: Fix 'Watch how it works' button redirection. Add new page for access-code registeration.
  src/App.js
  src/components/FrameComponent4.js
  src/components/PlatformOverview.js
  src/pages/AccessCodeRegisteration.js
Labels: good first issue, Hacktoberfest, Hacktoberfest-accepted
